// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: ElecrowScreen

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_rpmbackgreen;
lv_obj_t * ui_rpmbackblue;
lv_obj_t * ui_rpmbackred;
lv_obj_t * ui_erpmbackswitchup;
lv_obj_t * ui_erpmbackswitchdown;
lv_obj_t * ui_erpmbar;
lv_obj_t * ui_rpmtextback;
lv_obj_t * ui_rpmfrontgreen;
lv_obj_t * ui_rpmfrontblue;
lv_obj_t * ui_rpmfrontred;
lv_obj_t * ui_rpmdu;
lv_obj_t * ui_erpm;
lv_obj_t * ui_geardu;
lv_obj_t * ui_egear;
lv_obj_t * ui_eengineback;
lv_obj_t * ui_enginedu;
lv_obj_t * ui_eengine;
lv_obj_t * ui_evoltageback;
lv_obj_t * ui_voltagedu;
lv_obj_t * ui_evoltage;
lv_obj_t * ui_eoiltemperatureback;
lv_obj_t * ui_oiltemperaturedu;
lv_obj_t * ui_eoiltemperature;
lv_obj_t * ui_speeddu;
lv_obj_t * ui_espeed;
lv_obj_t * ui_eoilpressureback;
lv_obj_t * ui_oilpressuredu;
lv_obj_t * ui_eoilpressure;
lv_obj_t * ui_espeedarc;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
