// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: ElecrowScreen

#ifndef _ELECROWSCREEN_UI_H
#define _ELECROWSCREEN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_rpmbackgreen;
extern lv_obj_t * ui_rpmbackblue;
extern lv_obj_t * ui_rpmbackred;
extern lv_obj_t * ui_erpmbackswitchup;
extern lv_obj_t * ui_erpmbackswitchdown;
extern lv_obj_t * ui_erpmbar;
extern lv_obj_t * ui_rpmtextback;
extern lv_obj_t * ui_rpmfrontgreen;
extern lv_obj_t * ui_rpmfrontblue;
extern lv_obj_t * ui_rpmfrontred;
extern lv_obj_t * ui_rpmdu;
extern lv_obj_t * ui_erpm;
extern lv_obj_t * ui_geardu;
extern lv_obj_t * ui_egear;
extern lv_obj_t * ui_eengineback;
extern lv_obj_t * ui_enginedu;
extern lv_obj_t * ui_eengine;
extern lv_obj_t * ui_evoltageback;
extern lv_obj_t * ui_voltagedu;
extern lv_obj_t * ui_evoltage;
extern lv_obj_t * ui_eoiltemperatureback;
extern lv_obj_t * ui_oiltemperaturedu;
extern lv_obj_t * ui_eoiltemperature;
extern lv_obj_t * ui_speeddu;
extern lv_obj_t * ui_espeed;
extern lv_obj_t * ui_eoilpressureback;
extern lv_obj_t * ui_oilpressuredu;
extern lv_obj_t * ui_eoilpressure;
extern lv_obj_t * ui_espeedarc;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font100);
LV_FONT_DECLARE(ui_font_Font150);
LV_FONT_DECLARE(ui_font_Font250);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif